// Generated by scripts/build-edge.cjs
const C = (function(DATA){
  const clone=x=>JSON.parse(JSON.stringify(x));
  const fail=(message,status=400)=>{const e=new Error(message);e.status=status;throw e;};
  const blankScores=()=>Object.fromEntries(DATA.projects.map(p=>[p.id,Array(5).fill(null)]));
  const initial=()=>({schema:1,revision:0,finalized:false,finalizedAt:null,updatedAt:null,ballots:Object.fromEntries(DATA.judges.map(j=>[j.id,{revision:0,scores:blankScores(),submitted:false,submittedAt:null,updatedAt:null}])),audit:[]});
  const valid=n=>typeof n==='number'&&Number.isInteger(n)&&n>=0&&n<=20;
  const filled=s=>DATA.projects.reduce((n,p)=>n+s[p.id].filter(valid).length,0);
  const total=a=>a.every(valid)?a.reduce((x,y)=>x+y,0):null;
  function validate(scores){if(!scores||typeof scores!=='object'||Array.isArray(scores)||Object.keys(scores).length!==6)fail('6개 작품의 평가점수가 필요합니다.');for(const p of DATA.projects){const a=scores[p.id];if(!Array.isArray(a)||a.length!==5||a.some(n=>n!==null&&!valid(n)))fail('점수는 0~20 사이의 정수 또는 빈칸이어야 합니다.');}}
  function mutate(state,role,action,now=new Date().toISOString()){
    const s=clone(state);const admin=role==='admin';const b=s.ballots[role];
    if(!admin&&!b)fail('접근 권한이 없습니다.',403);
    if(['save','submit'].includes(action.type)){
      if(!b)fail('심사위원만 점수를 입력할 수 있습니다.',403);
      if(s.finalized||b.submitted)fail('제출된 심사표는 수정할 수 없습니다.',409);
      if(action.expectedRevision!==b.revision)fail('다른 화면에서 심사표가 변경되었습니다. 미저장 점수를 백업하고 최신 점수를 다시 불러오세요.',409);
      if(action.type==='save'){validate(action.scores);b.scores=clone(action.scores);}
      if(action.type==='submit'){if(filled(b.scores)!==30)fail('6개 작품의 30개 항목을 모두 입력해야 합니다.');b.submitted=true;b.submittedAt=now;}
      b.revision++;b.updatedAt=now;
    }else if(action.type==='finalize'){
      if(!admin)fail('운영자만 전체 심사를 완료할 수 있습니다.',403);
      if(s.finalized)fail('이미 완료된 심사입니다.',409);
      if(!Object.values(s.ballots).every(b=>b.submitted&&filled(b.scores)===30))fail('심사위원 5명 모두 심사표를 제출해야 합니다.');
      s.finalized=true;s.finalizedAt=now;
    }else if(action.type==='reopen'){
      if(!admin)fail('운영자만 수정 요청을 처리할 수 있습니다.',403);
      if(typeof action.reason!=='string'||action.reason.trim().length<2||action.reason.length>500)fail('수정 사유를 2~500자로 입력하세요.');
      const target=s.ballots[action.judgeId];if(!target)fail('심사위원을 확인하세요.');
      target.submitted=false;target.submittedAt=null;target.revision++;target.updatedAt=now;s.finalized=false;s.finalizedAt=null;
    }else fail('지원하지 않는 요청입니다.');
    s.revision++;s.updatedAt=now;
    s.audit.push({at:now,role,type:action.type,judgeId:action.judgeId||role,reason:action.reason||'',revision:s.revision});
    return s;
  }
  function visible(state,role){const s=clone(state);if(role!=='admin')for(const [id,b] of Object.entries(s.ballots))if(id!==role){b.filled=filled(b.scores);b.scores=null;}if(role!=='admin')s.audit=[];return s;}
  function ranking(state){if(!state.finalized)fail('전체 심사 완료 후 결과를 확인할 수 있습니다.');const result=[];
    for(const category of ['시민','공무원']){
      const list=DATA.projects.filter(p=>p.category===category).map(p=>{const scores=DATA.judges.map(j=>total(state.ballots[j.id].scores[p.id]));if(scores.some(x=>x===null))fail('미입력 점수가 있습니다.');const sum=scores.reduce((a,b)=>a+b,0);return {...p,scores,sum,average:sum/5};}).sort((a,b)=>b.sum-a.sum);
      list.forEach((p,i)=>{p.rank=1+list.filter(q=>q.sum>p.sum).length;p.tied=list.filter(q=>q.sum===p.sum).length>1;p.award=p.tied?'협의 필요':['대상','최우수상','우수상'][p.rank-1];});result.push(...list);
    }return result;
  }
  return {DATA,clone,initial,blankScores,valid,filled,total,validate,mutate,visible,ranking};
})({
  "event": "2026 AI화성 챌린지",
  "date": "2026. 9. 17.(목)",
  "location": "화성시청 3층 대강당",
  "projects": [
    {
      "id": "p1",
      "name": "화성 온(ON)동네",
      "category": "시민",
      "description": "화성시 통합예약시스템에 모여 있는 문화·평생학습·체육 프로그램 정보를 공급자(행정) 분류 그대로가 아닌 시민의 의도 기준으로 재분류하고, AI 의미 태깅·자연어 검색·지도 탐색을 결합하여 “내 주변에서 지금 신청할 수 있는 프로그램”을 30초 안에 발견하도록 돕는 탐색 서비스입니다. 예약은 기존 통합예약시스템으로 연결하여 원천 시스템의 가치를 그대로 살리면서, 그 앞단의 ‘발견’ 경험을 시민 눈높이로 바꿉니다. 아울러 재분류 과정에서 시민 의도와 실제 공급 사이의 수요-공급 갭을 도출·목록화하여 프로그램 기획·선정에 활용할 수 있는 근거를 함께 제공합니다.",
      "url": "https://hwaseong-ondongne.vercel.app/",
      "presenter": "황선미",
      "field": "문화"
    },
    {
      "id": "p2",
      "name": "우리가게 길잡이",
      "category": "시민",
      "description": "\"동탄에서 카페를 차리려고 해\"처럼 자연어로 물으면, AI가 인허가 절차와 받을 수 있는 지원사업 등을 분석해 순서형 창업 로드맵을 제시합니다. 법제처 국가법령·화성시 조례·보조금24·기업마당·K-Startup 등 공공데이터를 연동하고, 법령은 실제 조문을 찾아 인용하는 RAG 방식으로 신뢰성을 높였습니다.",
      "url": "https://www.cayson.xyz",
      "presenter": "최무호",
      "field": "행정"
    },
    {
      "id": "p3",
      "name": "화성 아이닥터 맵",
      "category": "시민",
      "description": "화성 아이닥터 맵은 보호자에게는 현재 시간 기준으로 문을 연 소아청소년과와 증상별 안전 안내를 제공하고, 정책 담당자에게는 0-9세 아동 인구와 진료시간 데이터를 결합해 시간대별 소아 진료 공백과 추가 배치 후보를 보여주는 공공데이터 기반 웹서비스이다.  시민 뷰는 아이가 아픈 보호자가 설치 없이 브라우저에서 바로 사용할 수 있도록 구성했으며, 정책 뷰는 화성시의 소아 진료 접근성, 공백 우선순위, AI 배치 추천을 한 화면에서 비교하도록 구성했다.",
      "url": "https://hwaseong-idoctor-map-pearl.vercel.app/",
      "presenter": "김누리",
      "field": "복지"
    },
    {
      "id": "p4",
      "name": "WE-ONE",
      "category": "공무원",
      "description": "AI 기술과 공공데이터를 융합하여 민원인·영업자·공무원·시민을 유기적으로 연결하는 스마트 위생행정 데이터 플랫폼",
      "url": "https://we-one-hygiene-platform-k23z.vercel.app/",
      "presenter": "윤혜림",
      "field": "복지"
    },
    {
      "id": "p5",
      "name": "화성시 당직업무 통합 플랫폼",
      "category": "공무원",
      "description": "전화 및 온라인 민원을 AI가 실시간으로 분류하고, GIS 상황지도에서 접수·인력 출동·문자 전송까지 처리하는 통합 상황실 플랫폼",
      "url": "https://duty-management-platform.vercel.app/",
      "presenter": "이동재",
      "field": "행정"
    },
    {
      "id": "p6",
      "name": "공공 홈페이지 24시간 자동 점검 솔루션",
      "category": "공무원",
      "description": "무료 AI를 활용하여 공공 홈페이지의 맞춤법·표기·문맥 오류 등을 24시간 자동 점검하고 수정을 지원하는 웹 기반 솔루션",
      "url": "https://46-250-253-33.sslip.io/",
      "presenter": "이선아",
      "field": "행정"
    }
  ],
  "judges": [
    {
      "id": "j1",
      "name": "정희석",
      "affiliation": "정보통신과장"
    },
    {
      "id": "j2",
      "name": "김규진",
      "affiliation": "서신면장"
    },
    {
      "id": "j3",
      "name": "홍아름",
      "affiliation": "경희대학교 AI기술경영학과 학과장"
    },
    {
      "id": "j4",
      "name": "서호성",
      "affiliation": "행정안전부 혁신기획과 사무관"
    },
    {
      "id": "j5",
      "name": "정원석",
      "affiliation": "㈜에이아이큐브 대표이사"
    }
  ],
  "criteria": [
    {
      "name": "창의성",
      "max": 20,
      "description": "내용의 독창성 및 동일·유사 사례 여부"
    },
    {
      "name": "효율성",
      "max": 20,
      "description": "비용·인력 등 투입 대비 결과와 행정혁신 효과"
    },
    {
      "name": "적용범위",
      "max": 20,
      "description": "실제 적용 가능한 대상 및 수혜 대상의 범위"
    },
    {
      "name": "계속성",
      "max": 20,
      "description": "AI 활용의 점진적 확대를 위한 연차별 준비사항"
    },
    {
      "name": "기술성",
      "max": 20,
      "description": "핵심 기술의 실질적 구현 정도 및 출품작의 완성도"
    }
  ]
});
export default C;
