const {test}=require('node:test');const assert=require('node:assert/strict');const C=require('../lib/core.cjs');
const full=(value=20)=>Object.fromEntries(C.DATA.projects.map(p=>[p.id,Array(5).fill(value)]));
function complete(){let s=C.initial();for(const j of C.DATA.judges){s=C.mutate(s,j.id,{type:'save',scores:full(),expectedRevision:0});s=C.mutate(s,j.id,{type:'submit',expectedRevision:1});}return s;}
test('6 works, 5 judges, 5 criteria with 100 point total',()=>{assert.equal(C.DATA.projects.length,6);assert.equal(C.DATA.judges.length,5);assert.equal(C.DATA.criteria.reduce((s,c)=>s+c.max,0),100);assert.equal(C.filled(C.blankScores()),0);assert.equal(C.total([0,0,0,0,0]),0);assert.equal(C.total([20,20,null,20,20]),null);});
test('bounds, decimals, strings, missing fields are rejected',()=>{for(const v of [-1,21,1.2,'20',NaN]){const scores=full();scores.p1[0]=v;assert.throws(()=>C.validate(scores));}assert.throws(()=>C.validate({}));C.validate(full(0));});
test('missing scores and missing submissions block finalization',()=>{let s=C.initial();assert.throws(()=>C.mutate(s,'j1',{type:'submit',expectedRevision:0}));assert.throws(()=>C.mutate(s,'admin',{type:'finalize'}));s=C.mutate(s,'j1',{type:'save',scores:full(0),expectedRevision:0});s=C.mutate(s,'j1',{type:'submit',expectedRevision:1});assert.equal(s.ballots.j1.submitted,true);assert.throws(()=>C.mutate(s,'admin',{type:'finalize'}));});
test('completed scoring locks edits, total 500 and average 100, ties require deliberation',()=>{let s=complete();assert.throws(()=>C.mutate(s,'j1',{type:'save',scores:full(1),expectedRevision:2}));assert.throws(()=>C.mutate(s,'j1',{type:'finalize'}));s=C.mutate(s,'admin',{type:'finalize'});for(const row of C.ranking(s)){assert.equal(row.sum,500);assert.equal(row.average,100);assert.equal(row.rank,1);assert.equal(row.award,'협의 필요');}});
test('category ranking, competition ties, zero score, reopening audit',()=>{let s=C.initial();for(const j of C.DATA.judges){const scores=full();scores.p2.fill(18);scores.p3.fill(18);scores.p4.fill(0);scores.p5.fill(10);scores.p6.fill(20);s=C.mutate(s,j.id,{type:'save',scores,expectedRevision:0});s=C.mutate(s,j.id,{type:'submit',expectedRevision:1});}s=C.mutate(s,'admin',{type:'finalize'});const r=C.ranking(s);assert.deepEqual(r.map(x=>x.rank),[1,2,2,1,2,3]);assert.equal(r.find(x=>x.id==='p4').sum,0);assert.equal(r.find(x=>x.id==='p2').sum,450);assert.equal(r.find(x=>x.id==='p6').award,'대상');s=C.mutate(s,'admin',{type:'reopen',judgeId:'j1',reason:'기술성 점수 확인'});assert.equal(s.finalized,false);assert.equal(s.ballots.j1.submitted,false);assert.equal(s.audit.at(-1).reason,'기술성 점수 확인');assert.throws(()=>C.ranking(s));assert.throws(()=>C.mutate(s,'admin',{type:'finalize'}));});
test('revision protects against stale overwrites and judges cannot see other scores',()=>{const s=C.mutate(C.initial(),'j1',{type:'save',scores:full(18),expectedRevision:0});assert.throws(()=>C.mutate(s,'j1',{type:'save',scores:full(10),expectedRevision:0}),/다른 화면/);assert.throws(()=>C.mutate(s,'j2',{type:'reopen',judgeId:'j1',reason:'수정'}));const v=C.visible(s,'j2');assert.equal(v.ballots.j1.scores,null);assert.equal(v.ballots.j1.filled,30);assert.deepEqual(v.audit,[]);assert.ok(C.visible(s,'admin').ballots.j1.scores);});
test('inline scripts and standalone file syntax',()=>{const fs=require('node:fs'),vm=require('node:vm');const html=fs.readFileSync(require('node:path').join(__dirname,'../dist/index.html'),'utf8');for(const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);assert(!html.includes('/*__DATA__*/'));assert(!html.includes('/*__CORE__*/'));assert(!/<script[^>]+src=/.test(html));assert(!/010-\d{4}-\d{4}/.test(html));});
