(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./core.cjs'));else root.JudgingPrint=factory(root.Judging);})(typeof window!=='undefined'?window:globalThis,function(C){
  const D=C.DATA,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function signatures(){return `<section class="signature-section"><h2>심사위원 확인 및 서명</h2><div class="signature-intro"><span>위 심사결과의 집계내용을 확인합니다.</span><span>확인일: ______년 ____월 ____일</span></div><table class="signature-table" aria-label="심사위원 5명 서명란"><thead><tr>${D.judges.map(j=>`<th scope="col">심사위원 ${esc(j.name)}</th>`).join('')}</tr></thead><tbody><tr>${D.judges.map(j=>`<td aria-label="${esc(j.name)} 자필 서명란"><span class="sign-label">(서명)</span></td>`).join('')}</tr></tbody></table></section>`;}
  function render(state){
    const rows=C.ranking(state),tied=rows.some(r=>r.tied);
    return `<article class="paper"><header class="paper-head"><p class="paper-event">${esc(D.event)} · 시민·공무원 최종 발표심사</p><h1>최종 심사결과 집계표</h1><div class="paper-meta"><span>심사일: ${esc(D.date)} / ${esc(D.location)}</span><span>심사위원 5명 · 심사대상 6작품</span></div></header>${['시민','공무원'].map(cat=>`<section class="paper-group"><h2>□ ${cat} 부문</h2><table class="paper-results" aria-label="${cat} 부문 최종 심사결과"><colgroup><col style="width:5%"><col style="width:29%">${D.judges.map(()=>'<col style="width:7%">').join('')}<col style="width:10%"><col style="width:10%"><col style="width:11%"></colgroup><thead><tr><th scope="col">순위</th><th scope="col">작품명 / 발표자</th>${D.judges.map(j=>`<th scope="col">${esc(j.name)}</th>`).join('')}<th scope="col">합계<br>(500점)</th><th scope="col">평균<br>(100점)</th><th scope="col">수상등급<br>(참고)</th></tr></thead><tbody>${rows.filter(r=>r.category===cat).map(r=>`<tr><td>${r.tied?'공동 ':''}${r.rank}</td><td class="paper-work"><strong>${esc(r.name)}</strong><span>${esc(r.presenter)}</span></td>${r.scores.map(n=>`<td>${n}</td>`).join('')}<td><strong>${r.sum}</strong></td><td>${r.average.toFixed(2)}</td><td>${esc(r.award)}</td></tr>`).join('')}</tbody></table></section>`).join('')}<p class="paper-note">※ 창의성·효율성·적용범위·계속성·기술성 각 20점 / 합계: 5명 점수 합산 / 평균: 합계 ÷ 5<br>※ ${tied?'동점 작품은 공동순위로 표시하였으며, 최종 수상등급은 심사위원 협의가 필요합니다.':'수상등급은 점수 순위에 따른 참고 표시이며, 최종 시상은 심사위원회 결정에 따릅니다.'}</p>${signatures()}<footer class="paper-footer">집계일시: ${esc(new Date(state.finalizedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))} (한국시간)</footer></article>`;
  }
  function ballot(state,judgeId){
    const j=D.judges.find(j=>j.id===judgeId),b=state.ballots[judgeId];
    if(!j||!b?.scores)throw Error('출력할 심사표를 확인할 수 없습니다.');
    C.validate(b.scores);
    return `<article class="paper ballot-paper"><header class="paper-head"><p class="paper-event">${esc(D.event)} · 시민·공무원 최종 발표심사</p><h1>개별 심사표 ${b.submitted?'(제출 완료)':'(미제출 · 확인용)'}</h1><div class="paper-meta"><span>${esc(D.date)} 10:00 / ${esc(D.location)}</span><span>심사위원: ${esc(j.name)} / ${esc(j.affiliation)}</span></div></header><table class="paper-results"><colgroup><col style="width:7%"><col style="width:33%"><col style="width:10%"><col style="width:10%"><col style="width:10%"><col style="width:10%"><col style="width:10%"><col style="width:10%"></colgroup><thead><tr><th>부문</th><th>작품명 / 발표자</th>${D.criteria.map(c=>`<th>${esc(c.name)}<br>(${c.max}점)</th>`).join('')}<th>합계<br>(100점)</th></tr></thead><tbody>${D.projects.map(p=>`<tr><td>${esc(p.category)}</td><td class="paper-work"><strong>${esc(p.name)}</strong><span>${esc(p.presenter)}</span></td>${b.scores[p.id].map(n=>`<td>${n===null?'미입력':n}</td>`).join('')}<td><strong>${C.total(b.scores[p.id])??'미입력'}</strong></td></tr>`).join('')}</tbody></table><p class="paper-note">※ 각 항목은 0~20점, 작품별 100점 만점입니다. 미입력은 0점과 구분됩니다.<br>※ ${b.submitted?'서버에 제출된 심사점수입니다.':'현재 저장된 점수의 확인용 출력물이며 최종 제출본이 아닙니다.'}</p><section class="signature-section"><h2>심사위원 확인</h2><p>위 심사내용을 확인합니다.</p><p style="text-align:right;margin-top:12mm">2026년 9월 17일　　심사위원 ${esc(j.name)}　　________________ (서명)</p></section><footer class="paper-footer">${b.submittedAt?'제출일시: '+esc(new Date(b.submittedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))+' (한국시간)':'미제출 · 확인용'}</footer></article>`;
  }
  return {render,signatures,ballot};
});
