(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./core.cjs'));else root.JudgingPrint=factory(root.Judging);})(typeof window!=='undefined'?window:globalThis,function(C){
  const D=C.DATA,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function signatures(){return `<section class="signature-section"><h2>심사위원 확인 및 서명</h2><div class="signature-intro"><span>위 심사결과의 집계내용을 확인합니다.</span><span>확인일: ______년 ____월 ____일</span></div><table class="signature-table" aria-label="심사위원 5명 서명란"><thead><tr>${D.judges.map(j=>`<th scope="col">심사위원 ${esc(j.name)}</th>`).join('')}</tr></thead><tbody><tr>${D.judges.map(j=>`<td aria-label="${esc(j.name)} 자필 서명란"><span class="sign-label">(서명)</span></td>`).join('')}</tr></tbody></table></section>`;}
  function render(state){
    const rows=C.ranking(state),tied=rows.some(r=>r.tied);
    return `<article class="paper"><header class="paper-head"><p class="paper-event">${esc(D.event)} · 시민·공무원 최종 발표심사</p><h1>최종 심사결과 집계표</h1><div class="paper-meta"><span>심사일: ${esc(D.date)} / ${esc(D.location)}</span><span>심사위원 5명 · 심사대상 6작품</span></div></header>${['시민','공무원'].map(cat=>`<section class="paper-group"><h2>□ ${cat} 부문</h2><table class="paper-results" aria-label="${cat} 부문 최종 심사결과"><colgroup><col style="width:5%"><col style="width:29%">${D.judges.map(()=>'<col style="width:7%">').join('')}<col style="width:10%"><col style="width:10%"><col style="width:11%"></colgroup><thead><tr><th scope="col">순위</th><th scope="col">작품명 / 발표자</th>${D.judges.map(j=>`<th scope="col">${esc(j.name)}</th>`).join('')}<th scope="col">합계<br>(500점)</th><th scope="col">평균<br>(100점)</th><th scope="col">수상등급<br>(참고)</th></tr></thead><tbody>${rows.filter(r=>r.category===cat).map(r=>`<tr><td>${r.tied?'공동 ':''}${r.rank}</td><td class="paper-work"><strong>${esc(r.name)}</strong><span>${esc(r.presenter)}</span></td>${r.scores.map(n=>`<td>${n}</td>`).join('')}<td><strong>${r.sum}</strong></td><td>${r.average.toFixed(2)}</td><td>${esc(r.award)}</td></tr>`).join('')}</tbody></table></section>`).join('')}<p class="paper-note">※ 창의성·효율성·적용범위·계속성·기술성 각 20점 / 합계: 5명 점수 합산 / 평균: 합계 ÷ 5<br>※ ${tied?'동점 작품은 공동순위로 표시하였으며, 최종 수상등급은 심사위원 협의가 필요합니다.':'수상등급은 점수 순위에 따른 참고 표시이며, 최종 시상은 심사위원회 결정에 따릅니다.'}</p>${signatures()}<footer class="paper-footer">집계일시: ${esc(new Date(state.finalizedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))} (한국시간)</footer></article>`;
  }
  return {render,signatures};
});
