const fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..');
const source=fs.readFileSync(path.join(root,'lib/core.cjs'),'utf8');
const body=source.slice(source.indexOf('function(DATA){')+'function(DATA){'.length,source.lastIndexOf('});'));
const data=fs.readFileSync(path.join(root,'lib/data.json'),'utf8');
fs.writeFileSync(path.join(root,'supabase/functions/judging-state/core.mjs'),'// Generated by scripts/build-edge.cjs\nconst C = (function(DATA){'+body+'})('+data+');\nexport default C;\n');
